/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Frames;

/**
 *
 * @author je110
 */
public class TombolaGUI extends javax.swing.JPanel {

    /**
     * Creates new form Tombola
     */
    public TombolaGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        lbl5 = new javax.swing.JLabel();
        lbl6 = new javax.swing.JLabel();
        lbl7 = new javax.swing.JLabel();
        lbl8 = new javax.swing.JLabel();
        lbl9 = new javax.swing.JLabel();
        lbl10 = new javax.swing.JLabel();
        lbl11 = new javax.swing.JLabel();
        lbl12 = new javax.swing.JLabel();
        lbl13 = new javax.swing.JLabel();
        lbl14 = new javax.swing.JLabel();
        lbl15 = new javax.swing.JLabel();
        lbl16 = new javax.swing.JLabel();
        lbl17 = new javax.swing.JLabel();
        lbl18 = new javax.swing.JLabel();
        lbl19 = new javax.swing.JLabel();
        lbl20 = new javax.swing.JLabel();
        lbl21 = new javax.swing.JLabel();
        lbl22 = new javax.swing.JLabel();
        lbl23 = new javax.swing.JLabel();
        lbl24 = new javax.swing.JLabel();
        lbl25 = new javax.swing.JLabel();
        lbl26 = new javax.swing.JLabel();
        lbl27 = new javax.swing.JLabel();
        lbl28 = new javax.swing.JLabel();
        lbl29 = new javax.swing.JLabel();
        lbl30 = new javax.swing.JLabel();
        lbl31 = new javax.swing.JLabel();
        lbl32 = new javax.swing.JLabel();
        lbl33 = new javax.swing.JLabel();
        lbl34 = new javax.swing.JLabel();
        lbl35 = new javax.swing.JLabel();
        lbl36 = new javax.swing.JLabel();
        lbl37 = new javax.swing.JLabel();
        lbl38 = new javax.swing.JLabel();
        lbl39 = new javax.swing.JLabel();
        lbl40 = new javax.swing.JLabel();
        lbl41 = new javax.swing.JLabel();
        lbl42 = new javax.swing.JLabel();
        lbl43 = new javax.swing.JLabel();
        lbl44 = new javax.swing.JLabel();
        lbl45 = new javax.swing.JLabel();
        lbl46 = new javax.swing.JLabel();
        lbl47 = new javax.swing.JLabel();
        lbl48 = new javax.swing.JLabel();
        lbl49 = new javax.swing.JLabel();
        lbl50 = new javax.swing.JLabel();
        lbl51 = new javax.swing.JLabel();
        lbl52 = new javax.swing.JLabel();
        lbl53 = new javax.swing.JLabel();
        lbl54 = new javax.swing.JLabel();
        lbl55 = new javax.swing.JLabel();
        lbl56 = new javax.swing.JLabel();
        lbl57 = new javax.swing.JLabel();
        lbl58 = new javax.swing.JLabel();
        lbl59 = new javax.swing.JLabel();
        lbl60 = new javax.swing.JLabel();
        lbl61 = new javax.swing.JLabel();
        lbl62 = new javax.swing.JLabel();
        lbl63 = new javax.swing.JLabel();
        lbl64 = new javax.swing.JLabel();
        lbl65 = new javax.swing.JLabel();
        lbl66 = new javax.swing.JLabel();
        lbl67 = new javax.swing.JLabel();
        lbl68 = new javax.swing.JLabel();
        lbl69 = new javax.swing.JLabel();
        lbl70 = new javax.swing.JLabel();
        lbl71 = new javax.swing.JLabel();
        lbl72 = new javax.swing.JLabel();
        lbl73 = new javax.swing.JLabel();
        lbl74 = new javax.swing.JLabel();
        lbl75 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(10, 14, 39));

        jPanel2.setBackground(new java.awt.Color(10, 14, 39));
        jPanel2.setLayout(new java.awt.GridLayout(5, 14));

        lbl1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl1.setText("1");
        lbl1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl1);

        lbl2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl2.setText("2");
        lbl2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl2);

        lbl3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl3.setText("3");
        lbl3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl3);

        lbl4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl4.setText("4");
        lbl4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl4);

        lbl5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl5.setText("5");
        lbl5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl5);

        lbl6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl6.setText("6");
        lbl6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl6);

        lbl7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl7.setText("7");
        lbl7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl7);

        lbl8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl8.setText("8");
        lbl8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl8);

        lbl9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl9.setText("9");
        lbl9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl9);

        lbl10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl10.setText("10");
        lbl10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl10);

        lbl11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl11.setText("11");
        lbl11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl11);

        lbl12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl12.setText("12");
        lbl12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl12);

        lbl13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl13.setText("13");
        lbl13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl13);

        lbl14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl14.setText("14");
        lbl14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl14);

        lbl15.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl15.setText("15");
        lbl15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl15);

        lbl16.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl16.setText("16");
        lbl16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl16);

        lbl17.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl17.setText("17");
        lbl17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl17);

        lbl18.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl18.setText("18");
        lbl18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl18);

        lbl19.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl19.setText("19");
        lbl19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl19);

        lbl20.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl20.setText("20");
        lbl20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl20.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl20);

        lbl21.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl21.setText("21");
        lbl21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl21.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl21);

        lbl22.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl22.setText("22");
        lbl22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl22.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl22);

        lbl23.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl23.setText("23");
        lbl23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl23);

        lbl24.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl24.setText("24");
        lbl24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl24.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl24);

        lbl25.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl25.setText("25");
        lbl25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl25.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl25);

        lbl26.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl26.setText("26");
        lbl26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl26.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl26);

        lbl27.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl27.setText("27");
        lbl27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl27.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl27);

        lbl28.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl28.setText("28");
        lbl28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl28.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl28);

        lbl29.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl29.setText("29");
        lbl29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl29.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl29);

        lbl30.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl30.setText("30");
        lbl30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl30.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl30);

        lbl31.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl31.setText("31");
        lbl31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl31.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl31);

        lbl32.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl32.setText("32");
        lbl32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl32.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl32);

        lbl33.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl33.setText("33");
        lbl33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl33.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl33);

        lbl34.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl34.setText("34");
        lbl34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl34.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl34);

        lbl35.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl35.setText("35");
        lbl35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl35.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl35);

        lbl36.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl36.setText("36");
        lbl36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl36.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl36);

        lbl37.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl37.setText("37");
        lbl37.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl37.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl37);

        lbl38.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl38.setText("38");
        lbl38.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl38.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl38);

        lbl39.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl39.setText("39");
        lbl39.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl39.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl39);

        lbl40.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl40.setText("40");
        lbl40.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl40.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl40);

        lbl41.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl41.setText("41");
        lbl41.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl41.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl41);

        lbl42.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl42.setText("42");
        lbl42.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl42.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl42);

        lbl43.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl43.setText("43");
        lbl43.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl43.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl43);

        lbl44.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl44.setText("44");
        lbl44.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl44.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl44);

        lbl45.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl45.setText("45");
        lbl45.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl45.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl45);

        lbl46.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl46.setText("46");
        lbl46.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl46.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl46);

        lbl47.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl47.setText("47");
        lbl47.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl47.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl47);

        lbl48.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl48.setText("48");
        lbl48.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl48.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl48);

        lbl49.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl49.setText("49");
        lbl49.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl49.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl49);

        lbl50.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl50.setText("50");
        lbl50.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl50.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl50);

        lbl51.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl51.setText("51");
        lbl51.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl51.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl51);

        lbl52.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl52.setText("52");
        lbl52.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl52.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl52);

        lbl53.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl53.setText("53");
        lbl53.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl53.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl53);

        lbl54.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl54.setText("54");
        lbl54.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl54.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl54);

        lbl55.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl55.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl55.setText("55");
        lbl55.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl55.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl55);

        lbl56.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl56.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl56.setText("56");
        lbl56.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl56.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl56);

        lbl57.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl57.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl57.setText("57");
        lbl57.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl57.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl57);

        lbl58.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl58.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl58.setText("58");
        lbl58.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl58.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl58);

        lbl59.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl59.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl59.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl59.setText("59");
        lbl59.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl59.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl59);

        lbl60.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl60.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl60.setText("60");
        lbl60.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl60.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl60);

        lbl61.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl61.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl61.setText("61");
        lbl61.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl61.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl61);

        lbl62.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl62.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl62.setText("62");
        lbl62.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl62.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl62);

        lbl63.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl63.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl63.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl63.setText("63");
        lbl63.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl63.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl63);

        lbl64.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl64.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl64.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl64.setText("64");
        lbl64.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl64.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl64);

        lbl65.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl65.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl65.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl65.setText("65");
        lbl65.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl65.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl65);

        lbl66.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl66.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl66.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl66.setText("66");
        lbl66.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl66.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl66);

        lbl67.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl67.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl67.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl67.setText("67");
        lbl67.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl67.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl67);

        lbl68.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl68.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl68.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl68.setText("68");
        lbl68.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl68.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl68);

        lbl69.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl69.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl69.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl69.setText("69");
        lbl69.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl69.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl69);

        lbl70.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl70.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl70.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl70.setText("70");
        lbl70.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl70.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl70);

        lbl71.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl71.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl71.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl71.setText("71");
        lbl71.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl71.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl71);

        lbl72.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl72.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl72.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl72.setText("72");
        lbl72.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl72.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl72);

        lbl73.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl73.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl73.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl73.setText("73");
        lbl73.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl73.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl73);

        lbl74.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl74.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl74.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl74.setText("74");
        lbl74.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl74.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl74);

        lbl75.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl75.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl75.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cuadrito.png"))); // NOI18N
        lbl75.setText("75");
        lbl75.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 63, 81)));
        lbl75.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl75);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/B.png"))); // NOI18N

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/I.png"))); // NOI18N

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/N.png"))); // NOI18N

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/G.png"))); // NOI18N

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/O.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 996, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl10;
    private javax.swing.JLabel lbl11;
    private javax.swing.JLabel lbl12;
    private javax.swing.JLabel lbl13;
    private javax.swing.JLabel lbl14;
    private javax.swing.JLabel lbl15;
    private javax.swing.JLabel lbl16;
    private javax.swing.JLabel lbl17;
    private javax.swing.JLabel lbl18;
    private javax.swing.JLabel lbl19;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl20;
    private javax.swing.JLabel lbl21;
    private javax.swing.JLabel lbl22;
    private javax.swing.JLabel lbl23;
    private javax.swing.JLabel lbl24;
    private javax.swing.JLabel lbl25;
    private javax.swing.JLabel lbl26;
    private javax.swing.JLabel lbl27;
    private javax.swing.JLabel lbl28;
    private javax.swing.JLabel lbl29;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl30;
    private javax.swing.JLabel lbl31;
    private javax.swing.JLabel lbl32;
    private javax.swing.JLabel lbl33;
    private javax.swing.JLabel lbl34;
    private javax.swing.JLabel lbl35;
    private javax.swing.JLabel lbl36;
    private javax.swing.JLabel lbl37;
    private javax.swing.JLabel lbl38;
    private javax.swing.JLabel lbl39;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl40;
    private javax.swing.JLabel lbl41;
    private javax.swing.JLabel lbl42;
    private javax.swing.JLabel lbl43;
    private javax.swing.JLabel lbl44;
    private javax.swing.JLabel lbl45;
    private javax.swing.JLabel lbl46;
    private javax.swing.JLabel lbl47;
    private javax.swing.JLabel lbl48;
    private javax.swing.JLabel lbl49;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl50;
    private javax.swing.JLabel lbl51;
    private javax.swing.JLabel lbl52;
    private javax.swing.JLabel lbl53;
    private javax.swing.JLabel lbl54;
    private javax.swing.JLabel lbl55;
    private javax.swing.JLabel lbl56;
    private javax.swing.JLabel lbl57;
    private javax.swing.JLabel lbl58;
    private javax.swing.JLabel lbl59;
    private javax.swing.JLabel lbl6;
    private javax.swing.JLabel lbl60;
    private javax.swing.JLabel lbl61;
    private javax.swing.JLabel lbl62;
    private javax.swing.JLabel lbl63;
    private javax.swing.JLabel lbl64;
    private javax.swing.JLabel lbl65;
    private javax.swing.JLabel lbl66;
    private javax.swing.JLabel lbl67;
    private javax.swing.JLabel lbl68;
    private javax.swing.JLabel lbl69;
    private javax.swing.JLabel lbl7;
    private javax.swing.JLabel lbl70;
    private javax.swing.JLabel lbl71;
    private javax.swing.JLabel lbl72;
    private javax.swing.JLabel lbl73;
    private javax.swing.JLabel lbl74;
    private javax.swing.JLabel lbl75;
    private javax.swing.JLabel lbl8;
    private javax.swing.JLabel lbl9;
    // End of variables declaration//GEN-END:variables
}
