/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

//import javax.swing.JOptionPane;
//import src.controller.JuegoController;
//import model.core.Juego;
//import model.enums.ModoJuego;
//import view.PanelCartones;
/**
 *
 * @author je110
 */
public class Inicio extends javax.swing.JFrame {
    //private JuegoController juegoController;
    //private PanelCartones panelCartones;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Inicio.class.getName());

    /**
     * Creates new form ConfiguracionDelJuego
     */
    public Inicio() {
        initComponents();
        //rbLlenadoAuto.setSelected(true);
        //rbMarcadoAuto.setSelected(true);
        //rbNormal.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblIcon = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblIcon2 = new javax.swing.JLabel();
        lblLlenado = new javax.swing.JLabel();
        btnAutomatico = new javax.swing.JButton();
        btnManual = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblIcon3 = new javax.swing.JLabel();
        btnAutomatico2 = new javax.swing.JButton();
        btnManual2 = new javax.swing.JButton();
        lblMarcado = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblIcon4 = new javax.swing.JLabel();
        lblModoJuego = new javax.swing.JLabel();
        btnCuatroEsquinas = new javax.swing.JButton();
        btnNormal = new javax.swing.JButton();
        btnLleno = new javax.swing.JButton();
        lblNormal = new javax.swing.JLabel();
        lblCuatroEsquinas = new javax.swing.JLabel();
        lblLleno = new javax.swing.JLabel();
        btnIniciarJuego = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Configuraciones");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(10, 14, 39));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Configuración.png"))); // NOI18N

        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Bingo.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(44, 63, 81));

        lblIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Dado.png"))); // NOI18N

        lblLlenado.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblLlenado.setForeground(new java.awt.Color(10, 14, 39));
        lblLlenado.setText("Modo de Llenado:");

        btnAutomatico.setBackground(new java.awt.Color(44, 63, 81));
        btnAutomatico.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAutomatico.setForeground(new java.awt.Color(255, 255, 255));
        btnAutomatico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/automatico.png"))); // NOI18N
        btnAutomatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutomaticoActionPerformed(evt);
            }
        });

        btnManual.setBackground(new java.awt.Color(44, 63, 81));
        btnManual.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnManual.setForeground(new java.awt.Color(255, 255, 255));
        btnManual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/manual.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblIcon2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblLlenado)
                        .addGap(327, 327, 327))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnAutomatico, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnManual, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblIcon2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lblLlenado, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnManual, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnAutomatico, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(44, 63, 81));

        lblIcon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Lapiz.png"))); // NOI18N

        btnAutomatico2.setBackground(new java.awt.Color(44, 63, 81));
        btnAutomatico2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAutomatico2.setForeground(new java.awt.Color(255, 255, 255));
        btnAutomatico2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/automatico.png"))); // NOI18N
        btnAutomatico2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutomatico2ActionPerformed(evt);
            }
        });

        btnManual2.setBackground(new java.awt.Color(44, 63, 81));
        btnManual2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnManual2.setForeground(new java.awt.Color(255, 255, 255));
        btnManual2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/manual.png"))); // NOI18N

        lblMarcado.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblMarcado.setForeground(new java.awt.Color(10, 14, 39));
        lblMarcado.setText("Modo de Marcado:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblIcon3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMarcado)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAutomatico2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(btnManual2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lblIcon3)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblMarcado, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAutomatico2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManual2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
        );

        jPanel4.setBackground(new java.awt.Color(44, 63, 81));

        lblIcon4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Play.png"))); // NOI18N

        lblModoJuego.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblModoJuego.setForeground(new java.awt.Color(10, 14, 39));
        lblModoJuego.setText("Modo de Juego:");

        btnCuatroEsquinas.setBackground(new java.awt.Color(18, 43, 62));
        btnCuatroEsquinas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/CuatroEsquinas.png"))); // NOI18N

        btnNormal.setBackground(new java.awt.Color(18, 43, 62));
        btnNormal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/normal.png"))); // NOI18N
        btnNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNormalActionPerformed(evt);
            }
        });

        btnLleno.setBackground(new java.awt.Color(18, 43, 62));
        btnLleno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Lleno.jpg"))); // NOI18N

        lblNormal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNormal.setForeground(new java.awt.Color(10, 14, 39));
        lblNormal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNormal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Normal (2).png"))); // NOI18N

        lblCuatroEsquinas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCuatroEsquinas.setForeground(new java.awt.Color(10, 14, 39));
        lblCuatroEsquinas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCuatroEsquinas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/CuatroEsquinas (2).png"))); // NOI18N

        lblLleno.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblLleno.setForeground(new java.awt.Color(10, 14, 39));
        lblLleno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLleno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Lleno.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblIcon4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblModoJuego)
                        .addContainerGap(363, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnNormal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNormal, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnLleno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLleno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCuatroEsquinas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCuatroEsquinas, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblModoJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIcon4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNormal)
                            .addComponent(btnLleno)
                            .addComponent(btnCuatroEsquinas))
                        .addContainerGap(21, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(lblNormal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(lblCuatroEsquinas, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(lblLleno, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42))))))
        );

        btnIniciarJuego.setBackground(new java.awt.Color(10, 14, 39));
        btnIniciarJuego.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnIniciarJuego.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Iniciar.png"))); // NOI18N
        btnIniciarJuego.setBorder(null);
        btnIniciarJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarJuegoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(lblIcon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTitulo)
                        .addGap(0, 199, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnIniciarJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(220, 220, 220))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIcon)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIniciarJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
  //private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {                                           
          // Validar llenado
    //if (!rbLlenadoAuto.isSelected() && !rbLlenadoManual.isSelected()) {
        //JOptionPane.showMessageDialog(this, 
            //"Debe seleccionar un Modo de Llenado.");
        //return;
    //}

    // Validar marcado
    //if (!rbMarcadoAuto.isSelected() && !rbMarcadoManual.isSelected()) {
        //JOptionPane.showMessageDialog(this, 
            //"Debe seleccionar un Modo de Marcado.");
        //return;
    //}

    // Validar modo de juego
    //if (!rbNormal.isSelected() && 
        //!rbCuatroEsquinas.isSelected() &&
        //!rbCartonLleno.isSelected()) 
    //{
        //JOptionPane.showMessageDialog(this, 
            //"Debe seleccionar un Modo de Juego.");
        //return;
    //}

    // ✔ Si pasa todas las validaciones:

    //boolean llenadoAuto = rbLlenadoAuto.isSelected();
    //boolean marcadoAuto = rbMarcadoAuto.isSelected();

    //ModoJuego modo;
    //if (rbCuatroEsquinas.isSelected()) {
        //modo = ModoJuego.CUATRO_ESQUINAS;
    //} else if (rbCartonLleno.isSelected()) {
        //modo = ModoJuego.CARTON_LLENO;
    //} else {
        //modo = ModoJuego.NORMAL;
    //}

    //Juego juego = new Juego();
    //juego.setModoJuego(modo);
    //juego.setMarcadoAutomatico(marcadoAuto);

    //JuegoController controller = new JuegoController(juego);

    //GameWindowForm gw = new GameWindowForm(controller, !marcadoAuto, llenadoAuto, modo);
    //gw.setVisible(true);
    //this.dispose();
    private void btnIniciarJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarJuegoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIniciarJuegoActionPerformed

    private void btnAutomaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutomaticoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAutomaticoActionPerformed

    private void btnAutomatico2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutomatico2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAutomatico2ActionPerformed

    private void btnNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNormalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNormalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(new Runnable() {
            //public void run() {
                //new StartWindowFrame().setVisible(true);
            //}
        //});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAutomatico;
    private javax.swing.JButton btnAutomatico2;
    private javax.swing.JButton btnCuatroEsquinas;
    private javax.swing.JButton btnIniciarJuego;
    private javax.swing.JButton btnLleno;
    private javax.swing.JButton btnManual;
    private javax.swing.JButton btnManual2;
    private javax.swing.JButton btnNormal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblCuatroEsquinas;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblIcon2;
    private javax.swing.JLabel lblIcon3;
    private javax.swing.JLabel lblIcon4;
    private javax.swing.JLabel lblLlenado;
    private javax.swing.JLabel lblLleno;
    private javax.swing.JLabel lblMarcado;
    private javax.swing.JLabel lblModoJuego;
    private javax.swing.JLabel lblNormal;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
