/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JOptionPane;
import Controlador.JuegoControlador;
import Modelo.Juego;
import Modelo.ModoJuego;
/**
 *
 * @author je110
 */
public class Inicio extends javax.swing.JFrame {
    private JuegoControlador juegoControlador;
    private PanelCartonesGUI panelCartones;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Inicio.class.getName());

    /**
     * Creates new form ConfiguracionDelJuego
     */
    public Inicio() {
        initComponents();
        btnLlenadoAutomatico.setSelected(true);
        btnMarcadoAutomatico.setSelected(true);
        btnNormal.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoLlenado = new javax.swing.ButtonGroup();
        grupoMarcado = new javax.swing.ButtonGroup();
        grupoModo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblIcon = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblIcon2 = new javax.swing.JLabel();
        lblLlenado = new javax.swing.JLabel();
        btnLlenadoAutomatico = new javax.swing.JRadioButton();
        btnLlenadoManual = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        lblIcon3 = new javax.swing.JLabel();
        lblMarcado = new javax.swing.JLabel();
        btnMarcadoAutomatico = new javax.swing.JRadioButton();
        btnMarcadoManual = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        lblIcon4 = new javax.swing.JLabel();
        lblModoJuego = new javax.swing.JLabel();
        lblNormal = new javax.swing.JLabel();
        lblCuatroEsquinas = new javax.swing.JLabel();
        lblLleno = new javax.swing.JLabel();
        btnNormal = new javax.swing.JRadioButton();
        btnLleno = new javax.swing.JRadioButton();
        btnCuatroEsquinas = new javax.swing.JRadioButton();
        btnIniciarJuego = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Configuraciones");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(10, 14, 39));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Configuración.png"))); // NOI18N

        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Bingo.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(44, 63, 81));

        lblIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Dado.png"))); // NOI18N

        lblLlenado.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblLlenado.setForeground(new java.awt.Color(10, 14, 39));
        lblLlenado.setText("Modo de Llenado:");

        grupoLlenado.add(btnLlenadoAutomatico);
        btnLlenadoAutomatico.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnLlenadoAutomatico.setForeground(new java.awt.Color(10, 14, 39));
        btnLlenadoAutomatico.setText("Automatico");

        grupoLlenado.add(btnLlenadoManual);
        btnLlenadoManual.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnLlenadoManual.setForeground(new java.awt.Color(10, 14, 39));
        btnLlenadoManual.setText("Manual");
        btnLlenadoManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLlenadoManualActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(lblIcon2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLlenado))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(btnLlenadoAutomatico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(56, 56, 56)
                .addComponent(btnLlenadoManual)
                .addGap(161, 161, 161))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblIcon2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lblLlenado, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLlenadoAutomatico)
                            .addComponent(btnLlenadoManual))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(44, 63, 81));

        lblIcon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Lapiz.png"))); // NOI18N

        lblMarcado.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblMarcado.setForeground(new java.awt.Color(10, 14, 39));
        lblMarcado.setText("Modo de Marcado:");

        grupoMarcado.add(btnMarcadoAutomatico);
        btnMarcadoAutomatico.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnMarcadoAutomatico.setForeground(new java.awt.Color(10, 14, 39));
        btnMarcadoAutomatico.setText("Automatico");

        grupoMarcado.add(btnMarcadoManual);
        btnMarcadoManual.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnMarcadoManual.setForeground(new java.awt.Color(10, 14, 39));
        btnMarcadoManual.setText("Manual");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lblIcon3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblMarcado)
                        .addGap(87, 87, 87))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnMarcadoAutomatico, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)))
                .addComponent(btnMarcadoManual)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblIcon3)
                .addGap(98, 98, 98))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMarcado, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMarcadoAutomatico)
                    .addComponent(btnMarcadoManual))
                .addGap(51, 51, 51))
        );

        jPanel4.setBackground(new java.awt.Color(44, 63, 81));

        lblIcon4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Play.png"))); // NOI18N

        lblModoJuego.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblModoJuego.setForeground(new java.awt.Color(10, 14, 39));
        lblModoJuego.setText("Modo de Juego:");

        lblNormal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNormal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNormal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Normal (2).png"))); // NOI18N

        lblCuatroEsquinas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCuatroEsquinas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCuatroEsquinas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/CuatroEsquinas (2).png"))); // NOI18N

        lblLleno.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblLleno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLleno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Lleno.png"))); // NOI18N

        grupoModo.add(btnNormal);

        grupoModo.add(btnLleno);

        grupoModo.add(btnCuatroEsquinas);
        btnCuatroEsquinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuatroEsquinasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblIcon4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblModoJuego)
                        .addContainerGap(363, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btnNormal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNormal)
                        .addGap(69, 69, 69)
                        .addComponent(btnLleno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLleno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCuatroEsquinas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCuatroEsquinas, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblModoJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIcon4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(btnNormal)
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(lblNormal, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnLleno)
                            .addComponent(lblLleno, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCuatroEsquinas)
                            .addComponent(lblCuatroEsquinas, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(42, 42, 42))))
        );

        btnIniciarJuego.setBackground(new java.awt.Color(10, 14, 39));
        btnIniciarJuego.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnIniciarJuego.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Iniciar.png"))); // NOI18N
        btnIniciarJuego.setBorder(null);
        btnIniciarJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarJuegoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(lblIcon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTitulo)
                        .addGap(0, 199, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(btnIniciarJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIcon)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIniciarJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnIniciarJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarJuegoActionPerformed
       if (!btnLlenadoAutomatico.isSelected() && !btnLlenadoManual.isSelected()) {
        JOptionPane.showMessageDialog(this, 
            "Debe seleccionar un Modo de Llenado.");
        return;
    }

    if (!btnMarcadoAutomatico.isSelected() && !btnMarcadoManual.isSelected()) {
        JOptionPane.showMessageDialog(this, 
            "Debe seleccionar un Modo de Marcado.");
        return;
    }

    if (!btnNormal.isSelected() && !btnCuatroEsquinas.isSelected() && !btnLleno.isSelected()) 
    {
        JOptionPane.showMessageDialog(this, 
            "Debe seleccionar un Modo de Juego.");
        return;
    }

    boolean llenadoAuto = btnLlenadoAutomatico.isSelected();
    boolean marcadoAuto = btnMarcadoAutomatico.isSelected();

    ModoJuego modo;
    if (btnCuatroEsquinas.isSelected()) {
        modo = ModoJuego.CUATROESQUINAS;
    } else if (btnLleno.isSelected()) {
        modo = ModoJuego.CARTONLLENO;
    } else {
        modo = ModoJuego.NORMAL;
    }

    Juego juego = new Juego();
    juego.setModoJuego(modo);
    juego.setMarcadoAutomatico(marcadoAuto);

    JuegoControlador controlador = new JuegoControlador(juego);

    JuegoGUI gw = new JuegoGUI(controlador, !marcadoAuto, llenadoAuto, modo);
    gw.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnIniciarJuegoActionPerformed

    private void btnLlenadoManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLlenadoManualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLlenadoManualActionPerformed

    private void btnCuatroEsquinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuatroEsquinasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCuatroEsquinasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnCuatroEsquinas;
    private javax.swing.JButton btnIniciarJuego;
    private javax.swing.JRadioButton btnLlenadoAutomatico;
    private javax.swing.JRadioButton btnLlenadoManual;
    private javax.swing.JRadioButton btnLleno;
    private javax.swing.JRadioButton btnMarcadoAutomatico;
    private javax.swing.JRadioButton btnMarcadoManual;
    private javax.swing.JRadioButton btnNormal;
    private javax.swing.ButtonGroup grupoLlenado;
    private javax.swing.ButtonGroup grupoMarcado;
    private javax.swing.ButtonGroup grupoModo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblCuatroEsquinas;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblIcon2;
    private javax.swing.JLabel lblIcon3;
    private javax.swing.JLabel lblIcon4;
    private javax.swing.JLabel lblLlenado;
    private javax.swing.JLabel lblLleno;
    private javax.swing.JLabel lblMarcado;
    private javax.swing.JLabel lblModoJuego;
    private javax.swing.JLabel lblNormal;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
