/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;


import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import Controlador.JuegoControlador;

/**
 *
 * @author Reynold
 */
public class LlenadoManualDialog extends javax.swing.JDialog {

     private final JuegoControlador controller;
    private final String idCarton;
    private boolean creado = false;
    private JTextField[][] campos;

    public LlenadoManualDialog(java.awt.Frame parent,
                           JuegoControlador controller,
                           String idCarton) {
    super(parent, true);
    this.controller = controller;
    this.idCarton = idCarton;
    initComponents();
    inicializarCampos();
    setLocationRelativeTo(parent);
}
    

    private void inicializarCampos() {
        campos = new JTextField[][]{
            {txt1, txt2, txt3, txt4, txt5},
            {txt6, txt7, txt8, txt9, txt10},
            {txt11, txt12, txt13, txt14, txt15},
            {txt16, txt17, txt18, txt19, txt20},
            {txt21, txt22, txt23, txt24, txt25}
        };

        for (int f = 0; f < 5; f++) {
            for (int c = 0; c < 5; c++) {
                campos[f][c].setHorizontalAlignment(JTextField.CENTER);
            }
        }

        txt13.setText("FREE");
        txt13.setEnabled(false);
    }

    private void crearCarton() {
        int[][] numeros = new int[5][5];

        for (int c = 0; c < 5; c++) {
            Set<Integer> usadosColumna = new HashSet<>();
            for (int f = 0; f < 5; f++) {
                if (f == 2 && c == 2) {
                    numeros[f][c] = 0;
                    continue;
                }

                String texto = campos[f][c].getText().trim();
                if (texto.isEmpty()) {
                    JOptionPane.showMessageDialog(this,
                            "Hay casillas vacías. Complete todos los números.",
                            "Error",
                            JOptionPane.ERROR_MESSAGE);
                    return;
                }

                int valor;
                try {
                    valor = Integer.parseInt(texto);
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(this,
                            "Solo se permiten números enteros.\nError en fila " + (f + 1) + ", columna " + (c + 1),
                            "Error",
                            JOptionPane.ERROR_MESSAGE);
                    return;
                }

                if (valor < 1 || valor > 75) {
                    JOptionPane.showMessageDialog(this,
                            "Número fuera de rango (1-75) en fila " + (f + 1) + ", columna " + (c + 1) + ".",
                            "Error",
                            JOptionPane.ERROR_MESSAGE);
                    return;
                }

                if (usadosColumna.contains(valor)) {
                    JOptionPane.showMessageDialog(this,
                            "Número repetido en la columna " + (c + 1) + ".",
                            "Error",
                            JOptionPane.ERROR_MESSAGE);
                    return;
                }

                usadosColumna.add(valor);
                numeros[f][c] = valor;
            }
        }

        if (controller.crearCartonManual(idCarton, numeros) == null) {
            JOptionPane.showMessageDialog(this,
                    "Ya existe un cartón con ese ID.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        creado = true;
        dispose();
    }

    public boolean fueCreado() {
        return creado;
    }
    
    /**
     * Creates new form LlenadoManualDialog
     */
    

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        panelBotones = new javax.swing.JPanel();
        btnCrear = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        panelGrid = new javax.swing.JPanel();
        txt1 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        txt3 = new javax.swing.JTextField();
        txt4 = new javax.swing.JTextField();
        txt5 = new javax.swing.JTextField();
        txt6 = new javax.swing.JTextField();
        txt7 = new javax.swing.JTextField();
        txt8 = new javax.swing.JTextField();
        txt9 = new javax.swing.JTextField();
        txt10 = new javax.swing.JTextField();
        txt11 = new javax.swing.JTextField();
        txt12 = new javax.swing.JTextField();
        txt13 = new javax.swing.JTextField();
        txt14 = new javax.swing.JTextField();
        txt15 = new javax.swing.JTextField();
        txt16 = new javax.swing.JTextField();
        txt17 = new javax.swing.JTextField();
        txt18 = new javax.swing.JTextField();
        txt19 = new javax.swing.JTextField();
        txt20 = new javax.swing.JTextField();
        txt21 = new javax.swing.JTextField();
        txt22 = new javax.swing.JTextField();
        txt23 = new javax.swing.JTextField();
        txt24 = new javax.swing.JTextField();
        txt25 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        LabelB = new javax.swing.JLabel();
        LabelI = new javax.swing.JLabel();
        LabelN = new javax.swing.JLabel();
        LabelG = new javax.swing.JLabel();
        LabelO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LLENADO MANUAL");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        panelBotones.setBackground(new java.awt.Color(51, 51, 51));
        panelBotones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        panelBotones.setName("panelBotones"); // NOI18N

        btnCrear.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnCrear.setText("Crear Carton");
        btnCrear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotonesLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        panelGrid.setBackground(new java.awt.Color(51, 51, 51));
        panelGrid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        panelGrid.setName("panelGrid"); // NOI18N
        panelGrid.setLayout(new java.awt.GridLayout(5, 5, 5, 5));

        txt1.setBackground(new java.awt.Color(51, 51, 51));
        txt1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        txt1.setForeground(new java.awt.Color(255, 255, 255));
        txt1.setActionCommand("null");
        txt1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txt1.setOpaque(true);
        txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt1ActionPerformed(evt);
            }
        });
        panelGrid.add(txt1);

        txt2.setBackground(new java.awt.Color(51, 51, 51));
        txt2.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        txt2.setForeground(new java.awt.Color(255, 255, 255));
        txt2.setActionCommand("null");
        txt2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txt2.setOpaque(true);
        panelGrid.add(txt2);

        txt3.setBackground(new java.awt.Color(51, 51, 51));
        txt3.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        txt3.setForeground(new java.awt.Color(255, 255, 255));
        txt3.setActionCommand("null");
        txt3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txt3.setOpaque(true);
        panelGrid.add(txt3);

        txt4.setBackground(new java.awt.Color(51, 51, 51));
        txt4.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        txt4.setForeground(new java.awt.Color(255, 255, 255));
        txt4.setActionCommand("null");
        txt4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txt4.setOpaque(true);
        panelGrid.add(txt4);

        txt5.setBackground(new java.awt.Color(51, 51, 51));
        txt5.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        txt5.setForeground(new java.awt.Color(255, 255, 255));
        txt5.setActionCommand("null");
        txt5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txt5.setOpaque(true);
        panelGrid.add(txt5);

        txt6.setBackground(new java.awt.Color(51, 51, 51));
        txt6.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        txt6.setForeground(new java.awt.Color(255, 255, 255));
        txt6.setActionCommand("null");
        txt6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txt6.setOpaque(true);
        panelGrid.add(txt6);

        txt7.setBackground(new java.awt.Color(51, 51, 51));
        txt7.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        txt7.setForeground(new java.awt.Color(255, 255, 255));
        txt7.setActionCommand("null");
        txt7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txt7.setOpaque(true);
        panelGrid.add(txt7);

        txt8.setBackground(new java.awt.Color(51, 51, 51));
        txt8.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        txt8.setForeground(new java.awt.Color(255, 255, 255));
        txt8.setActionCommand("null");
        txt8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txt8.setOpaque(true);
        panelGrid.add(txt8);

        txt9.setBackground(new java.awt.Color(51, 51, 51));
        txt9.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        txt9.setForeground(new java.awt.Color(255, 255, 255));
        txt9.setActionCommand("null");
        txt9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txt9.setOpaque(true);
        panelGrid.add(txt9);

        txt10.setBackground(new java.awt.Color(51, 51, 51));
        txt10.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        txt10.setForeground(new java.awt.Color(255, 255, 255));
        txt10.setActionCommand("null");
        txt10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txt10.setOpaque(true);
        panelGrid.add(txt10);

        txt11.setBackground(new java.awt.Color(51, 51, 51));
        txt11.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        txt11.setForeground(new java.awt.Color(255, 255, 255));
        txt11.setActionCommand("null");
        txt11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txt11.setOpaque(true);
        panelGrid.add(txt11);

        txt12.setBackground(new java.awt.Color(51, 51, 51));
        txt12.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        txt12.setForeground(new java.awt.Color(255, 255, 255));
        txt12.setActionCommand("null");
        txt12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txt12.setOpaque(true);
        panelGrid.add(txt12);

        txt13.setBackground(new java.awt.Color(51, 51, 51));
        txt13.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        txt13.setForeground(new java.awt.Color(255, 255, 255));
        txt13.setActionCommand("null");
        txt13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txt13.setOpaque(true);
        panelGrid.add(txt13);

        txt14.setBackground(new java.awt.Color(51, 51, 51));
        txt14.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        txt14.setForeground(new java.awt.Color(255, 255, 255));
        txt14.setActionCommand("null");
        txt14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txt14.setOpaque(true);
        panelGrid.add(txt14);

        txt15.setBackground(new java.awt.Color(51, 51, 51));
        txt15.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        txt15.setForeground(new java.awt.Color(255, 255, 255));
        txt15.setActionCommand("null");
        txt15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txt15.setOpaque(true);
        panelGrid.add(txt15);

        txt16.setBackground(new java.awt.Color(51, 51, 51));
        txt16.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        txt16.setForeground(new java.awt.Color(255, 255, 255));
        txt16.setActionCommand("null");
        txt16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txt16.setOpaque(true);
        panelGrid.add(txt16);

        txt17.setBackground(new java.awt.Color(51, 51, 51));
        txt17.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        txt17.setForeground(new java.awt.Color(255, 255, 255));
        txt17.setActionCommand("null");
        txt17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txt17.setOpaque(true);
        panelGrid.add(txt17);

        txt18.setBackground(new java.awt.Color(51, 51, 51));
        txt18.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        txt18.setForeground(new java.awt.Color(255, 255, 255));
        txt18.setActionCommand("null");
        txt18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txt18.setOpaque(true);
        panelGrid.add(txt18);

        txt19.setBackground(new java.awt.Color(51, 51, 51));
        txt19.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        txt19.setForeground(new java.awt.Color(255, 255, 255));
        txt19.setActionCommand("null");
        txt19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txt19.setOpaque(true);
        panelGrid.add(txt19);

        txt20.setBackground(new java.awt.Color(51, 51, 51));
        txt20.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        txt20.setForeground(new java.awt.Color(255, 255, 255));
        txt20.setActionCommand("null");
        txt20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txt20.setOpaque(true);
        panelGrid.add(txt20);

        txt21.setBackground(new java.awt.Color(51, 51, 51));
        txt21.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        txt21.setForeground(new java.awt.Color(255, 255, 255));
        txt21.setActionCommand("null");
        txt21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txt21.setOpaque(true);
        panelGrid.add(txt21);

        txt22.setBackground(new java.awt.Color(51, 51, 51));
        txt22.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        txt22.setForeground(new java.awt.Color(255, 255, 255));
        txt22.setActionCommand("null");
        txt22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txt22.setOpaque(true);
        panelGrid.add(txt22);

        txt23.setBackground(new java.awt.Color(51, 51, 51));
        txt23.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        txt23.setForeground(new java.awt.Color(255, 255, 255));
        txt23.setActionCommand("null");
        txt23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txt23.setOpaque(true);
        panelGrid.add(txt23);

        txt24.setBackground(new java.awt.Color(51, 51, 51));
        txt24.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        txt24.setForeground(new java.awt.Color(255, 255, 255));
        txt24.setActionCommand("null");
        txt24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txt24.setOpaque(true);
        panelGrid.add(txt24);

        txt25.setBackground(new java.awt.Color(51, 51, 51));
        txt25.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        txt25.setForeground(new java.awt.Color(255, 255, 255));
        txt25.setActionCommand("null");
        txt25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txt25.setOpaque(true);
        panelGrid.add(txt25);

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel3.setLayout(new java.awt.GridLayout(1, 5));

        LabelB.setBackground(new java.awt.Color(51, 51, 51));
        LabelB.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        LabelB.setForeground(new java.awt.Color(255, 0, 0));
        LabelB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelB.setText("B");
        LabelB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        LabelB.setOpaque(true);
        jPanel3.add(LabelB);

        LabelI.setBackground(new java.awt.Color(51, 51, 51));
        LabelI.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        LabelI.setForeground(new java.awt.Color(255, 255, 51));
        LabelI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelI.setText("I");
        LabelI.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        LabelI.setOpaque(true);
        jPanel3.add(LabelI);

        LabelN.setBackground(new java.awt.Color(51, 51, 51));
        LabelN.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        LabelN.setForeground(new java.awt.Color(0, 204, 153));
        LabelN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelN.setText("N");
        LabelN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        LabelN.setOpaque(true);
        jPanel3.add(LabelN);

        LabelG.setBackground(new java.awt.Color(51, 51, 51));
        LabelG.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        LabelG.setForeground(new java.awt.Color(51, 153, 255));
        LabelG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelG.setText("G");
        LabelG.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        LabelG.setOpaque(true);
        jPanel3.add(LabelG);

        LabelO.setBackground(new java.awt.Color(51, 51, 51));
        LabelO.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        LabelO.setForeground(new java.awt.Color(153, 51, 255));
        LabelO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelO.setText("O");
        LabelO.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        LabelO.setOpaque(true);
        jPanel3.add(LabelO);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelGrid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelGrid, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt1ActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
         crearCarton();
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        creado = false;
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelB;
    private javax.swing.JLabel LabelG;
    private javax.swing.JLabel LabelI;
    private javax.swing.JLabel LabelN;
    private javax.swing.JLabel LabelO;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelGrid;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt10;
    private javax.swing.JTextField txt11;
    private javax.swing.JTextField txt12;
    private javax.swing.JTextField txt13;
    private javax.swing.JTextField txt14;
    private javax.swing.JTextField txt15;
    private javax.swing.JTextField txt16;
    private javax.swing.JTextField txt17;
    private javax.swing.JTextField txt18;
    private javax.swing.JTextField txt19;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt20;
    private javax.swing.JTextField txt21;
    private javax.swing.JTextField txt22;
    private javax.swing.JTextField txt23;
    private javax.swing.JTextField txt24;
    private javax.swing.JTextField txt25;
    private javax.swing.JTextField txt3;
    private javax.swing.JTextField txt4;
    private javax.swing.JTextField txt5;
    private javax.swing.JTextField txt6;
    private javax.swing.JTextField txt7;
    private javax.swing.JTextField txt8;
    private javax.swing.JTextField txt9;
    // End of variables declaration//GEN-END:variables
}
