/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import java.awt.BorderLayout;
import java.awt.Color;
import static java.awt.Color.BLACK;
import java.awt.Dimension;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.Timer;


/**
 *
 * @author Valdelomaar
 */
public class PanelEstadoGanadores extends javax.swing.JPanel {
   

   
    private Animaciones animator;

    public PanelEstadoGanadores() {
        initComponents();
        inicializarAnimaciones();
        setEstadoGanador(false);
    }

    

    private void inicializarAnimaciones() {
    
        setLayout(new BorderLayout());
        setOpaque(false);  

       
       

        add(labelAnimacion, BorderLayout.CENTER);  

        animator = new Animaciones(labelAnimacion, 90);
    }

    public void setEstadoGanador(boolean hayGanadores) {
            if (hayGanadores) {

            labelEstadoGanadores.setVisible(false);  

            labelAnimacion.setVisible(true);
            animator.start();  
        } else {

            labelEstadoGanadores.setVisible(true);  
            labelEstadoGanadores.setText("SIN GANADORES TODAVÍA");  
            labelAnimacion.setVisible(false);        
            animator.stop();  
        }
        revalidate();
        repaint(); 
    }
    
    
    
    
    /**
     * Creates new form PanelEstadoGanadores
     */
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelAnimacion = new javax.swing.JLabel();
        labelEstadoGanadores = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        labelAnimacion.setForeground(new java.awt.Color(255, 255, 255));
        labelAnimacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(labelAnimacion, java.awt.BorderLayout.CENTER);

        labelEstadoGanadores.setFont(new java.awt.Font("Impact", 0, 17)); // NOI18N
        labelEstadoGanadores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelEstadoGanadores.setText("No hay ganadores");
        labelEstadoGanadores.setPreferredSize(new java.awt.Dimension(300, 50));
        add(labelEstadoGanadores, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelAnimacion;
    private javax.swing.JLabel labelEstadoGanadores;
    // End of variables declaration//GEN-END:variables
}
