/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import java.awt.GridLayout;
import Controlador.JuegoControlador;
import Modelo.Carton;
/**
 *
 * @author je110
 */
public class PanelCartonesGUI extends javax.swing.JPanel {
    private JuegoControlador controlador;

    public PanelCartonesGUI(JuegoControlador controlador) {
        this.controlador = controlador;
        setLayout(new GridLayout(0, 3, 10, 10));
    }

    public void refrescarCartones() {
        removeAll();

        for (Carton c : controlador.getCartones()) {
            CartonGUI cv = new CartonGUI();
            cv.mostrarCarton(c);
            add(cv);
        }

        revalidate();
        repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridLayout(1, 3, 10, 10));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
