/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Modelo.Animaciones;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Window;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;

/**
 *
 * @author Student
 */
public class PanelGanadorGUI extends javax.swing.JPanel {

    /**
     * Creates new form PanelGanadorGUI
     */ 
    private Animaciones animFelicidades;


    public PanelGanadorGUI() {
        initComponents();
        animFelicidades = new Animaciones(labelFelicidades, 90,300,300);
    }


    public void iniciarAnimacionFelicidades() {
        animFelicidades.start();
    }

    public void detenerAnimacionFelicidades() {
        animFelicidades.stop();
    }



    public void insertarCarton(javax.swing.JPanel panel) {
        PanelSlot.removeAll();

        if (!(PanelSlot.getLayout() instanceof BorderLayout)) {
            PanelSlot.setLayout(new BorderLayout());
        }
        
        PanelSlot.add(panel);
        PanelSlot.revalidate();
        PanelSlot.repaint();
    }

    public javax.swing.JButton getBotonOK() {
        return btnOK;
    }
     
    

    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelSlot = new javax.swing.JPanel();
        PanelBoton = new javax.swing.JPanel();
        btnOK = new javax.swing.JButton();
        panelFelicidades = new javax.swing.JPanel();
        labelFelicidades = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 102, 102));

        PanelSlot.setBackground(new java.awt.Color(102, 102, 102));
        PanelSlot.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout PanelSlotLayout = new javax.swing.GroupLayout(PanelSlot);
        PanelSlot.setLayout(PanelSlotLayout);
        PanelSlotLayout.setHorizontalGroup(
            PanelSlotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PanelSlotLayout.setVerticalGroup(
            PanelSlotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 347, Short.MAX_VALUE)
        );

        PanelBoton.setBackground(new java.awt.Color(102, 0, 153));

        btnOK.setBackground(new java.awt.Color(51, 51, 51));
        btnOK.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        btnOK.setForeground(new java.awt.Color(255, 255, 255));
        btnOK.setText("OK");
        btnOK.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelBotonLayout = new javax.swing.GroupLayout(PanelBoton);
        PanelBoton.setLayout(PanelBotonLayout);
        PanelBotonLayout.setHorizontalGroup(
            PanelBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBotonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnOK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelBotonLayout.setVerticalGroup(
            PanelBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBotonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelFelicidades.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        panelFelicidades.setMinimumSize(new java.awt.Dimension(400, 120));
        panelFelicidades.setOpaque(false);
        panelFelicidades.setPreferredSize(new java.awt.Dimension(400, 120));
        panelFelicidades.setLayout(new java.awt.BorderLayout());

        labelFelicidades.setBackground(new java.awt.Color(51, 51, 51));
        labelFelicidades.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFelicidades.setMinimumSize(new java.awt.Dimension(380, 110));
        labelFelicidades.setPreferredSize(new java.awt.Dimension(380, 110));
        panelFelicidades.add(labelFelicidades, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBoton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelSlot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelFelicidades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelFelicidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelSlot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelBoton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
         
    }//GEN-LAST:event_btnOKActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelBoton;
    private javax.swing.JPanel PanelSlot;
    private javax.swing.JButton btnOK;
    private javax.swing.JLabel labelFelicidades;
    private javax.swing.JPanel panelFelicidades;
    // End of variables declaration//GEN-END:variables
}
