/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.Timer;
import java.awt.Font;
/**
 *
 * @author samue
 */
public class TombolaGUI extends javax.swing.JPanel {
    private JLabel[] labelsNumeros;
    

    /**
     * Creates new form PanelTombolaUI
     */
    
 public TombolaGUI() {
    initComponents();
    inicializarArreglo();
    reiniciar();
}
 
   private void inicializarArreglo() {
    labelsNumeros = new JLabel[]{
        Label1, Label2, Label3, Label4, Label5,
        Label6, Label7, Label8, Label9, Label10,
        Label11, Label12, Label13, Label14, Label15,
        Label16, Label17, Label18, Label19, Label20,
        Label21, Label22, Label23, Label24, Label25,
        Label26, Label27, Label28, Label29, Label30,
        Label31, Label32, Label33, Label34, Label35,
        Label36, Label37, Label38, Label39, Label40,
        Label41, Label42, Label43, Label44, Label45,
        Label46, Label47, Label48, Label49, Label50,
        Label51, Label52, Label53, Label54, Label55,
        Label56, Label57, Label58, Label59, Label60,
        Label61, Label62, Label63, Label64, Label65,
        Label66, Label67, Label68, Label69, Label70,
        Label71, Label72, Label73, Label74, Label75
    };

    for (JLabel l : labelsNumeros) {
        l.setOpaque(true);
    }
}

   
   public void agregarNumero(int numero) {
    if (numero < 1 || numero > 75) return;

    JLabel lbl = labelsNumeros[numero - 1];
    lbl.setBackground(new Color(0, 170, 0));
    lbl.setForeground(Color.WHITE);

    // Animación visual "pop"
    animacionNumeroPop(lbl);
}
   
public void reiniciar() {
    for (JLabel lbl : labelsNumeros) {
        lbl.setBackground(new Color(45, 45, 45));
        lbl.setForeground(Color.WHITE);
    }
}
    

    private void animacionNumeroPop(JLabel lbl) {
        final int pasos = 8;
        final float tamañoBase = lbl.getFont().getSize2D();
        final float incremento = 3f; // cuánto crece

        final int[] step = {0};

        Timer t = new Timer(35, e -> {
            step[0]++;

            float factor;
            // primera mitad: crece, segunda: regresa al tamaño base
            if (step[0] <= pasos / 2) {
                factor = 1f + (step[0] * (incremento / tamañoBase) / (pasos / 2));
            } else {
                int pasoDesc = step[0] - pasos / 2;
                factor = 1f + ((incremento / tamañoBase) * ( (pasos / 2 - pasoDesc) / (float)(pasos / 2) ));
            }

            Font f = lbl.getFont();
            lbl.setFont(f.deriveFont(tamañoBase * factor));

            if (step[0] >= pasos) {
                ((Timer) e.getSource()).stop();
                // aseguramos que vuelva al tamaño original exacto
                lbl.setFont(f.deriveFont(tamañoBase));
            }
        });

        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Label1 = new javax.swing.JLabel();
        Label2 = new javax.swing.JLabel();
        Label3 = new javax.swing.JLabel();
        Label4 = new javax.swing.JLabel();
        Label5 = new javax.swing.JLabel();
        Label6 = new javax.swing.JLabel();
        Label7 = new javax.swing.JLabel();
        Label8 = new javax.swing.JLabel();
        Label9 = new javax.swing.JLabel();
        Label10 = new javax.swing.JLabel();
        Label11 = new javax.swing.JLabel();
        Label12 = new javax.swing.JLabel();
        Label13 = new javax.swing.JLabel();
        Label14 = new javax.swing.JLabel();
        Label15 = new javax.swing.JLabel();
        Label16 = new javax.swing.JLabel();
        Label17 = new javax.swing.JLabel();
        Label18 = new javax.swing.JLabel();
        Label19 = new javax.swing.JLabel();
        Label20 = new javax.swing.JLabel();
        Label21 = new javax.swing.JLabel();
        Label22 = new javax.swing.JLabel();
        Label23 = new javax.swing.JLabel();
        Label24 = new javax.swing.JLabel();
        Label25 = new javax.swing.JLabel();
        Label26 = new javax.swing.JLabel();
        Label27 = new javax.swing.JLabel();
        Label28 = new javax.swing.JLabel();
        Label29 = new javax.swing.JLabel();
        Label30 = new javax.swing.JLabel();
        Label31 = new javax.swing.JLabel();
        Label32 = new javax.swing.JLabel();
        Label33 = new javax.swing.JLabel();
        Label34 = new javax.swing.JLabel();
        Label35 = new javax.swing.JLabel();
        Label36 = new javax.swing.JLabel();
        Label37 = new javax.swing.JLabel();
        Label38 = new javax.swing.JLabel();
        Label39 = new javax.swing.JLabel();
        Label40 = new javax.swing.JLabel();
        Label41 = new javax.swing.JLabel();
        Label42 = new javax.swing.JLabel();
        Label43 = new javax.swing.JLabel();
        Label44 = new javax.swing.JLabel();
        Label45 = new javax.swing.JLabel();
        Label46 = new javax.swing.JLabel();
        Label47 = new javax.swing.JLabel();
        Label48 = new javax.swing.JLabel();
        Label49 = new javax.swing.JLabel();
        Label50 = new javax.swing.JLabel();
        Label51 = new javax.swing.JLabel();
        Label52 = new javax.swing.JLabel();
        Label53 = new javax.swing.JLabel();
        Label54 = new javax.swing.JLabel();
        Label55 = new javax.swing.JLabel();
        Label56 = new javax.swing.JLabel();
        Label57 = new javax.swing.JLabel();
        Label58 = new javax.swing.JLabel();
        Label59 = new javax.swing.JLabel();
        Label60 = new javax.swing.JLabel();
        Label61 = new javax.swing.JLabel();
        Label62 = new javax.swing.JLabel();
        Label63 = new javax.swing.JLabel();
        Label64 = new javax.swing.JLabel();
        Label65 = new javax.swing.JLabel();
        Label66 = new javax.swing.JLabel();
        Label67 = new javax.swing.JLabel();
        Label68 = new javax.swing.JLabel();
        Label69 = new javax.swing.JLabel();
        Label70 = new javax.swing.JLabel();
        Label71 = new javax.swing.JLabel();
        Label72 = new javax.swing.JLabel();
        Label73 = new javax.swing.JLabel();
        Label74 = new javax.swing.JLabel();
        Label75 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        LabelB = new javax.swing.JLabel();
        LabelI = new javax.swing.JLabel();
        LabelN = new javax.swing.JLabel();
        LabelG = new javax.swing.JLabel();
        LabelO = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(204, 204, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setLayout(new java.awt.GridLayout(5, 14));

        Label1.setBackground(new java.awt.Color(51, 51, 51));
        Label1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label1.setText("1");
        Label1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label1.setOpaque(true);
        jPanel1.add(Label1);

        Label2.setBackground(new java.awt.Color(51, 51, 51));
        Label2.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label2.setText("2");
        Label2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label2.setOpaque(true);
        jPanel1.add(Label2);

        Label3.setBackground(new java.awt.Color(51, 51, 51));
        Label3.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label3.setText("3");
        Label3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label3.setOpaque(true);
        jPanel1.add(Label3);

        Label4.setBackground(new java.awt.Color(51, 51, 51));
        Label4.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label4.setText("4");
        Label4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label4.setOpaque(true);
        jPanel1.add(Label4);

        Label5.setBackground(new java.awt.Color(51, 51, 51));
        Label5.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label5.setText("5");
        Label5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label5.setOpaque(true);
        jPanel1.add(Label5);

        Label6.setBackground(new java.awt.Color(51, 51, 51));
        Label6.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label6.setText("6");
        Label6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label6.setOpaque(true);
        jPanel1.add(Label6);

        Label7.setBackground(new java.awt.Color(51, 51, 51));
        Label7.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label7.setText("7");
        Label7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label7.setOpaque(true);
        jPanel1.add(Label7);

        Label8.setBackground(new java.awt.Color(51, 51, 51));
        Label8.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label8.setText("8");
        Label8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label8.setOpaque(true);
        jPanel1.add(Label8);

        Label9.setBackground(new java.awt.Color(51, 51, 51));
        Label9.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label9.setText("9");
        Label9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label9.setOpaque(true);
        jPanel1.add(Label9);

        Label10.setBackground(new java.awt.Color(51, 51, 51));
        Label10.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label10.setText("10");
        Label10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label10.setOpaque(true);
        jPanel1.add(Label10);

        Label11.setBackground(new java.awt.Color(51, 51, 51));
        Label11.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label11.setText("11");
        Label11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label11.setOpaque(true);
        jPanel1.add(Label11);

        Label12.setBackground(new java.awt.Color(51, 51, 51));
        Label12.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label12.setText("12");
        Label12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label12.setOpaque(true);
        jPanel1.add(Label12);

        Label13.setBackground(new java.awt.Color(51, 51, 51));
        Label13.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label13.setText("13");
        Label13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label13.setOpaque(true);
        jPanel1.add(Label13);

        Label14.setBackground(new java.awt.Color(51, 51, 51));
        Label14.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label14.setText("14");
        Label14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label14.setOpaque(true);
        jPanel1.add(Label14);

        Label15.setBackground(new java.awt.Color(51, 51, 51));
        Label15.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label15.setText("15");
        Label15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label15.setOpaque(true);
        jPanel1.add(Label15);

        Label16.setBackground(new java.awt.Color(51, 51, 51));
        Label16.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label16.setText("16");
        Label16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label16.setOpaque(true);
        jPanel1.add(Label16);

        Label17.setBackground(new java.awt.Color(51, 51, 51));
        Label17.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label17.setText("17");
        Label17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label17.setOpaque(true);
        jPanel1.add(Label17);

        Label18.setBackground(new java.awt.Color(51, 51, 51));
        Label18.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label18.setText("18");
        Label18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label18.setOpaque(true);
        jPanel1.add(Label18);

        Label19.setBackground(new java.awt.Color(51, 51, 51));
        Label19.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label19.setText("19");
        Label19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label19.setOpaque(true);
        jPanel1.add(Label19);

        Label20.setBackground(new java.awt.Color(51, 51, 51));
        Label20.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label20.setText("20");
        Label20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label20.setOpaque(true);
        jPanel1.add(Label20);

        Label21.setBackground(new java.awt.Color(51, 51, 51));
        Label21.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label21.setText("21");
        Label21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label21.setOpaque(true);
        jPanel1.add(Label21);

        Label22.setBackground(new java.awt.Color(51, 51, 51));
        Label22.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label22.setText("22");
        Label22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label22.setOpaque(true);
        jPanel1.add(Label22);

        Label23.setBackground(new java.awt.Color(51, 51, 51));
        Label23.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label23.setText("23");
        Label23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label23.setOpaque(true);
        jPanel1.add(Label23);

        Label24.setBackground(new java.awt.Color(51, 51, 51));
        Label24.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label24.setText("24");
        Label24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label24.setOpaque(true);
        jPanel1.add(Label24);

        Label25.setBackground(new java.awt.Color(51, 51, 51));
        Label25.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label25.setText("25");
        Label25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label25.setOpaque(true);
        jPanel1.add(Label25);

        Label26.setBackground(new java.awt.Color(51, 51, 51));
        Label26.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label26.setText("26");
        Label26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label26.setOpaque(true);
        jPanel1.add(Label26);

        Label27.setBackground(new java.awt.Color(51, 51, 51));
        Label27.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label27.setText("27");
        Label27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label27.setOpaque(true);
        jPanel1.add(Label27);

        Label28.setBackground(new java.awt.Color(51, 51, 51));
        Label28.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label28.setText("28");
        Label28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label28.setOpaque(true);
        jPanel1.add(Label28);

        Label29.setBackground(new java.awt.Color(51, 51, 51));
        Label29.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label29.setText("29");
        Label29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label29.setOpaque(true);
        jPanel1.add(Label29);

        Label30.setBackground(new java.awt.Color(51, 51, 51));
        Label30.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label30.setText("30");
        Label30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label30.setOpaque(true);
        jPanel1.add(Label30);

        Label31.setBackground(new java.awt.Color(51, 51, 51));
        Label31.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label31.setText("31");
        Label31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label31.setOpaque(true);
        jPanel1.add(Label31);

        Label32.setBackground(new java.awt.Color(51, 51, 51));
        Label32.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label32.setText("32");
        Label32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label32.setOpaque(true);
        jPanel1.add(Label32);

        Label33.setBackground(new java.awt.Color(51, 51, 51));
        Label33.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label33.setText("33");
        Label33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label33.setOpaque(true);
        jPanel1.add(Label33);

        Label34.setBackground(new java.awt.Color(51, 51, 51));
        Label34.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label34.setText("34");
        Label34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label34.setOpaque(true);
        jPanel1.add(Label34);

        Label35.setBackground(new java.awt.Color(51, 51, 51));
        Label35.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label35.setText("35");
        Label35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label35.setOpaque(true);
        jPanel1.add(Label35);

        Label36.setBackground(new java.awt.Color(51, 51, 51));
        Label36.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label36.setText("36");
        Label36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label36.setOpaque(true);
        jPanel1.add(Label36);

        Label37.setBackground(new java.awt.Color(51, 51, 51));
        Label37.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label37.setText("37");
        Label37.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label37.setOpaque(true);
        jPanel1.add(Label37);

        Label38.setBackground(new java.awt.Color(51, 51, 51));
        Label38.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label38.setText("38");
        Label38.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label38.setOpaque(true);
        jPanel1.add(Label38);

        Label39.setBackground(new java.awt.Color(51, 51, 51));
        Label39.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label39.setText("39");
        Label39.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label39.setOpaque(true);
        jPanel1.add(Label39);

        Label40.setBackground(new java.awt.Color(51, 51, 51));
        Label40.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label40.setText("40");
        Label40.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label40.setOpaque(true);
        jPanel1.add(Label40);

        Label41.setBackground(new java.awt.Color(51, 51, 51));
        Label41.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label41.setText("41");
        Label41.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label41.setOpaque(true);
        jPanel1.add(Label41);

        Label42.setBackground(new java.awt.Color(51, 51, 51));
        Label42.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label42.setText("42");
        Label42.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label42.setOpaque(true);
        jPanel1.add(Label42);

        Label43.setBackground(new java.awt.Color(51, 51, 51));
        Label43.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label43.setText("43");
        Label43.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label43.setOpaque(true);
        jPanel1.add(Label43);

        Label44.setBackground(new java.awt.Color(51, 51, 51));
        Label44.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label44.setText("44");
        Label44.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label44.setOpaque(true);
        jPanel1.add(Label44);

        Label45.setBackground(new java.awt.Color(51, 51, 51));
        Label45.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label45.setText("45");
        Label45.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label45.setOpaque(true);
        jPanel1.add(Label45);

        Label46.setBackground(new java.awt.Color(51, 51, 51));
        Label46.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label46.setText("46");
        Label46.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label46.setOpaque(true);
        jPanel1.add(Label46);

        Label47.setBackground(new java.awt.Color(51, 51, 51));
        Label47.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label47.setText("47");
        Label47.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label47.setOpaque(true);
        jPanel1.add(Label47);

        Label48.setBackground(new java.awt.Color(51, 51, 51));
        Label48.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label48.setText("48");
        Label48.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label48.setOpaque(true);
        jPanel1.add(Label48);

        Label49.setBackground(new java.awt.Color(51, 51, 51));
        Label49.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label49.setText("49");
        Label49.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label49.setOpaque(true);
        jPanel1.add(Label49);

        Label50.setBackground(new java.awt.Color(51, 51, 51));
        Label50.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label50.setText("50");
        Label50.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label50.setOpaque(true);
        jPanel1.add(Label50);

        Label51.setBackground(new java.awt.Color(51, 51, 51));
        Label51.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label51.setText("51");
        Label51.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label51.setOpaque(true);
        jPanel1.add(Label51);

        Label52.setBackground(new java.awt.Color(51, 51, 51));
        Label52.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label52.setText("52");
        Label52.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label52.setOpaque(true);
        jPanel1.add(Label52);

        Label53.setBackground(new java.awt.Color(51, 51, 51));
        Label53.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label53.setText("53");
        Label53.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label53.setOpaque(true);
        jPanel1.add(Label53);

        Label54.setBackground(new java.awt.Color(51, 51, 51));
        Label54.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label54.setText("54");
        Label54.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label54.setOpaque(true);
        jPanel1.add(Label54);

        Label55.setBackground(new java.awt.Color(51, 51, 51));
        Label55.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label55.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label55.setText("55");
        Label55.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label55.setOpaque(true);
        jPanel1.add(Label55);

        Label56.setBackground(new java.awt.Color(51, 51, 51));
        Label56.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label56.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label56.setText("56");
        Label56.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label56.setOpaque(true);
        jPanel1.add(Label56);

        Label57.setBackground(new java.awt.Color(51, 51, 51));
        Label57.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label57.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label57.setText("57");
        Label57.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label57.setOpaque(true);
        jPanel1.add(Label57);

        Label58.setBackground(new java.awt.Color(51, 51, 51));
        Label58.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label58.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label58.setText("58");
        Label58.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label58.setOpaque(true);
        jPanel1.add(Label58);

        Label59.setBackground(new java.awt.Color(51, 51, 51));
        Label59.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label59.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label59.setText("59");
        Label59.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label59.setOpaque(true);
        jPanel1.add(Label59);

        Label60.setBackground(new java.awt.Color(51, 51, 51));
        Label60.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label60.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label60.setText("60");
        Label60.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label60.setOpaque(true);
        jPanel1.add(Label60);

        Label61.setBackground(new java.awt.Color(51, 51, 51));
        Label61.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label61.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label61.setText("61");
        Label61.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label61.setOpaque(true);
        jPanel1.add(Label61);

        Label62.setBackground(new java.awt.Color(51, 51, 51));
        Label62.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label62.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label62.setText("62");
        Label62.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label62.setOpaque(true);
        jPanel1.add(Label62);

        Label63.setBackground(new java.awt.Color(51, 51, 51));
        Label63.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label63.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label63.setText("63");
        Label63.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label63.setOpaque(true);
        jPanel1.add(Label63);

        Label64.setBackground(new java.awt.Color(51, 51, 51));
        Label64.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label64.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label64.setText("64");
        Label64.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label64.setOpaque(true);
        jPanel1.add(Label64);

        Label65.setBackground(new java.awt.Color(51, 51, 51));
        Label65.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label65.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label65.setText("65");
        Label65.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label65.setOpaque(true);
        jPanel1.add(Label65);

        Label66.setBackground(new java.awt.Color(51, 51, 51));
        Label66.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label66.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label66.setText("66");
        Label66.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label66.setOpaque(true);
        jPanel1.add(Label66);

        Label67.setBackground(new java.awt.Color(51, 51, 51));
        Label67.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label67.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label67.setText("67");
        Label67.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label67.setOpaque(true);
        jPanel1.add(Label67);

        Label68.setBackground(new java.awt.Color(51, 51, 51));
        Label68.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label68.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label68.setText("68");
        Label68.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label68.setOpaque(true);
        jPanel1.add(Label68);

        Label69.setBackground(new java.awt.Color(51, 51, 51));
        Label69.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label69.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label69.setText("69");
        Label69.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label69.setOpaque(true);
        jPanel1.add(Label69);

        Label70.setBackground(new java.awt.Color(51, 51, 51));
        Label70.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label70.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label70.setText("70");
        Label70.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label70.setOpaque(true);
        jPanel1.add(Label70);

        Label71.setBackground(new java.awt.Color(51, 51, 51));
        Label71.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label71.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label71.setText("71");
        Label71.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label71.setOpaque(true);
        jPanel1.add(Label71);

        Label72.setBackground(new java.awt.Color(51, 51, 51));
        Label72.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label72.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label72.setText("72");
        Label72.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label72.setOpaque(true);
        jPanel1.add(Label72);

        Label73.setBackground(new java.awt.Color(51, 51, 51));
        Label73.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label73.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label73.setText("73");
        Label73.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label73.setOpaque(true);
        jPanel1.add(Label73);

        Label74.setBackground(new java.awt.Color(51, 51, 51));
        Label74.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label74.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label74.setText("74");
        Label74.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label74.setOpaque(true);
        jPanel1.add(Label74);

        Label75.setBackground(new java.awt.Color(51, 51, 51));
        Label75.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Label75.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label75.setText("75");
        Label75.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Label75.setOpaque(true);
        jPanel1.add(Label75);

        jPanel2.setBackground(new java.awt.Color(204, 204, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel2.setLayout(new java.awt.GridLayout(5, 0));

        LabelB.setBackground(new java.awt.Color(51, 51, 51));
        LabelB.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        LabelB.setForeground(new java.awt.Color(255, 0, 0));
        LabelB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelB.setText("B");
        LabelB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        LabelB.setOpaque(true);
        jPanel2.add(LabelB);

        LabelI.setBackground(new java.awt.Color(51, 51, 51));
        LabelI.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        LabelI.setForeground(new java.awt.Color(255, 255, 0));
        LabelI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelI.setText("I");
        LabelI.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        LabelI.setOpaque(true);
        jPanel2.add(LabelI);

        LabelN.setBackground(new java.awt.Color(51, 51, 51));
        LabelN.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        LabelN.setForeground(new java.awt.Color(0, 204, 153));
        LabelN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelN.setText("N");
        LabelN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        LabelN.setOpaque(true);
        jPanel2.add(LabelN);

        LabelG.setBackground(new java.awt.Color(51, 51, 51));
        LabelG.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        LabelG.setForeground(new java.awt.Color(51, 153, 255));
        LabelG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelG.setText("G");
        LabelG.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        LabelG.setOpaque(true);
        jPanel2.add(LabelG);

        LabelO.setBackground(new java.awt.Color(51, 51, 51));
        LabelO.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        LabelO.setForeground(new java.awt.Color(153, 0, 255));
        LabelO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelO.setText("O");
        LabelO.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        LabelO.setOpaque(true);
        jPanel2.add(LabelO);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1154, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label1;
    private javax.swing.JLabel Label10;
    private javax.swing.JLabel Label11;
    private javax.swing.JLabel Label12;
    private javax.swing.JLabel Label13;
    private javax.swing.JLabel Label14;
    private javax.swing.JLabel Label15;
    private javax.swing.JLabel Label16;
    private javax.swing.JLabel Label17;
    private javax.swing.JLabel Label18;
    private javax.swing.JLabel Label19;
    private javax.swing.JLabel Label2;
    private javax.swing.JLabel Label20;
    private javax.swing.JLabel Label21;
    private javax.swing.JLabel Label22;
    private javax.swing.JLabel Label23;
    private javax.swing.JLabel Label24;
    private javax.swing.JLabel Label25;
    private javax.swing.JLabel Label26;
    private javax.swing.JLabel Label27;
    private javax.swing.JLabel Label28;
    private javax.swing.JLabel Label29;
    private javax.swing.JLabel Label3;
    private javax.swing.JLabel Label30;
    private javax.swing.JLabel Label31;
    private javax.swing.JLabel Label32;
    private javax.swing.JLabel Label33;
    private javax.swing.JLabel Label34;
    private javax.swing.JLabel Label35;
    private javax.swing.JLabel Label36;
    private javax.swing.JLabel Label37;
    private javax.swing.JLabel Label38;
    private javax.swing.JLabel Label39;
    private javax.swing.JLabel Label4;
    private javax.swing.JLabel Label40;
    private javax.swing.JLabel Label41;
    private javax.swing.JLabel Label42;
    private javax.swing.JLabel Label43;
    private javax.swing.JLabel Label44;
    private javax.swing.JLabel Label45;
    private javax.swing.JLabel Label46;
    private javax.swing.JLabel Label47;
    private javax.swing.JLabel Label48;
    private javax.swing.JLabel Label49;
    private javax.swing.JLabel Label5;
    private javax.swing.JLabel Label50;
    private javax.swing.JLabel Label51;
    private javax.swing.JLabel Label52;
    private javax.swing.JLabel Label53;
    private javax.swing.JLabel Label54;
    private javax.swing.JLabel Label55;
    private javax.swing.JLabel Label56;
    private javax.swing.JLabel Label57;
    private javax.swing.JLabel Label58;
    private javax.swing.JLabel Label59;
    private javax.swing.JLabel Label6;
    private javax.swing.JLabel Label60;
    private javax.swing.JLabel Label61;
    private javax.swing.JLabel Label62;
    private javax.swing.JLabel Label63;
    private javax.swing.JLabel Label64;
    private javax.swing.JLabel Label65;
    private javax.swing.JLabel Label66;
    private javax.swing.JLabel Label67;
    private javax.swing.JLabel Label68;
    private javax.swing.JLabel Label69;
    private javax.swing.JLabel Label7;
    private javax.swing.JLabel Label70;
    private javax.swing.JLabel Label71;
    private javax.swing.JLabel Label72;
    private javax.swing.JLabel Label73;
    private javax.swing.JLabel Label74;
    private javax.swing.JLabel Label75;
    private javax.swing.JLabel Label8;
    private javax.swing.JLabel Label9;
    private javax.swing.JLabel LabelB;
    private javax.swing.JLabel LabelG;
    private javax.swing.JLabel LabelI;
    private javax.swing.JLabel LabelN;
    private javax.swing.JLabel LabelO;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
